/imu_node:
  ros__parameters:
    ~device_address: 105
    ~bus_id: 1
    ~imu_frame: 'imu_link'
    #~imu_pub_topic: '/imu/data'
    ~imu_pub_topic: '/imu/data_raw'
    ~publish_rate: 25
/imu_tf_pub:
  ros__parameters:
    ~imu_parent_link: 'plane'
    ~imu_link: 'imu_link'
    ~imu_sub_topic: '/imu/data'
